### ISSUE TITLE
two-handed stance never happening

### ISSUE THREAD

**Issue by f1re9arden** [TheRedBrain/bettercombat-extension#3]
hey, i'm on version 1.1.0 for 1.20.1 and i noticed that the character never uses the different variations of the two-handed idle stance across neither of the different weapon types and it remains using the default one instead. is this on purpose? i tried using default and modified config settings to no avail. uninstalling the mod fixes it. it would be cool to have the custom stances available!

with mod:
![2024-06-18_06 42 24](https://github.com/TheRedBrain/bettercombat-extension/assets/173148745/c52e44ce-279a-42e8-ac63-39f073da6019)
without mod:
![2024-06-18_06 57 04](https://github.com/TheRedBrain/bettercombat-extension/assets/173148745/fb7476da-57ef-4127-bc99-e317b0e1e2fb)

thank you

**Comment by TheRedBrain** [comment]
can you take a look at the weapon_attribute file of that weapon?

is "two_handed" set to true?
is there a field called "pose"?
and is there a field called "two_handed_pose"?

**Comment by TheRedBrain** [comment]
also, thank you for reporting this bug!

**Comment by TheRedBrain** [comment]
The toggleable two handed stance is an alternative to the two_handed boolean in the weapon_attribute file. This means that setting two_handed to true should make the weapon always two handed.
In order for the toggle to work, two_handed has to be set to false.

That being said, there is clearly an issue there, because in this case

> Heyo, came to report this actually but saw there was a thread already Two handed is set to true, pose field exists Added a two_handed_pose field with the same pose as the better combat one and it still doesn't work Even when I toggle stance with the RPG inventory mod it doesn't seem to work

the pose is clearly not correct.

I will investigate.
Thanks for the detailed report!

**Comment by TheRedBrain** [comment]
fixed in version 1.1.1
